name: Fichaje salida automático

on:
  schedule:
    # Lunes a jueves 17:00
    - cron: '00 15 * * 1-4'
    # Viernes a las 15:10
    - cron: '10 13 * * 5'
  workflow_dispatch:

jobs:
  fichar_salida:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Playwright y navegadores
        run: npx playwright install --with-deps

      - name: Ejecutar script de fichaje salida
        env:
          ERP_USER: ${{ secrets.ERP_USER }}
          ERP_PASS: ${{ secrets.ERP_PASS }}
        run: npm run salida